name: build-linux

permissions:
  contents: write

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        sudo apt install -y gcc xorg-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa wget

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: |
        mkdir -p dist/linux
        go build -v -ldflags="-s -w" -o dist/linux/HadesCrypt .
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Compress with upx
      run: |
        wget -O upx.tar.xz https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-amd64_linux.tar.xz
        tar -xf upx.tar.xz
        upx-5.0.2-amd64_linux/upx --lzma dist/linux/HadesCrypt

    - name: Get version
      run: |
        VERSION=$(cat VERSION | tr -d '\n\r')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Linux package
      run: |
        PACKAGE_NAME="HadesCrypt-v$VERSION-Linux-x64"
        mkdir -p "$PACKAGE_NAME/docs"
        
        # Copy executable
        cp dist/linux/HadesCrypt "$PACKAGE_NAME/"
        chmod +x "$PACKAGE_NAME/HadesCrypt"
        
        # Copy documentation
        cp README.md "$PACKAGE_NAME/docs/" 2>/dev/null || true
        cp CHANGELOG.md "$PACKAGE_NAME/docs/" 2>/dev/null || true
        
        # Create install script
        cat > "$PACKAGE_NAME/install.sh" << 'EOF'
#!/bin/bash
echo "Installing HadesCrypt..."
sudo cp HadesCrypt /usr/local/bin/hadescrypt
sudo chmod +x /usr/local/bin/hadescrypt
echo "HadesCrypt installed successfully!"
EOF
        chmod +x "$PACKAGE_NAME/install.sh"
        
        # Create tar.gz
        tar -czf "$PACKAGE_NAME.tar.gz" "$PACKAGE_NAME"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: |
          dist/linux/HadesCrypt
          HadesCrypt-v${{ env.VERSION }}-Linux-x64.tar.gz
        if-no-files-found: error
        compression-level: 9

    - name: Generate checksums
      run: |
        echo "CHECKSUM_HADESCRYPT=$(sha256sum dist/linux/HadesCrypt | cut -d ' ' -f1)" >> $GITHUB_ENV
        echo "CHECKSUM_PACKAGE=$(sha256sum HadesCrypt-v$VERSION-Linux-x64.tar.gz | cut -d ' ' -f1)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/linux/HadesCrypt
          HadesCrypt-v${{ env.VERSION }}-Linux-x64.tar.gz
        tag_name: v${{ env.VERSION }}
        name: HadesCrypt v${{ env.VERSION }}
        make_latest: true
        append_body: true
        body: |
          **Linux Build:**
          `sha256(HadesCrypt)      ${{ env.CHECKSUM_HADESCRYPT }}`
          `sha256(Package.tar.gz) ${{ env.CHECKSUM_PACKAGE }}`
