name: build-macos

permissions:
  contents: write

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        brew install glfw glew

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: |
        mkdir -p dist/macos
        go build -v -ldflags="-s -w" -o dist/macos/HadesCrypt .
      env:
        CGO_ENABLED: 1

    - name: Get version
      run: |
        VERSION=$(cat VERSION | tr -d '\n\r')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create macOS package
      run: |
        PACKAGE_NAME="HadesCrypt-v$VERSION-macOS-x64"
        mkdir -p "$PACKAGE_NAME/docs"
        
        # Copy executable
        cp dist/macos/HadesCrypt "$PACKAGE_NAME/"
        chmod +x "$PACKAGE_NAME/HadesCrypt"
        
        # Copy documentation
        cp README.md "$PACKAGE_NAME/docs/" 2>/dev/null || true
        cp CHANGELOG.md "$PACKAGE_NAME/docs/" 2>/dev/null || true
        
        # Create install script
        cat > "$PACKAGE_NAME/install.sh" << 'EOF'
#!/bin/bash
echo "Installing HadesCrypt..."
sudo cp HadesCrypt /usr/local/bin/hadescrypt
sudo chmod +x /usr/local/bin/hadescrypt
echo "HadesCrypt installed successfully!"
EOF
        chmod +x "$PACKAGE_NAME/install.sh"
        
        # Create tar.gz
        tar -czf "$PACKAGE_NAME.tar.gz" "$PACKAGE_NAME"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-macos
        path: |
          dist/macos/HadesCrypt
          HadesCrypt-v${{ env.VERSION }}-macOS-x64.tar.gz
        if-no-files-found: error
        compression-level: 9

    - name: Generate checksums
      run: |
        HASH1=$(shasum -a 256 dist/macos/HadesCrypt | cut -d ' ' -f1)
        HASH2=$(shasum -a 256 HadesCrypt-v$VERSION-macOS-x64.tar.gz | cut -d ' ' -f1)
        echo "CHECKSUM_HADESCRYPT=$HASH1" >> $GITHUB_ENV
        echo "CHECKSUM_PACKAGE=$HASH2" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/macos/HadesCrypt
          HadesCrypt-v${{ env.VERSION }}-macOS-x64.tar.gz
        tag_name: v${{ env.VERSION }}
        name: HadesCrypt v${{ env.VERSION }}
        make_latest: true
        append_body: true
        body: |
          **macOS Build:**
          `sha256(HadesCrypt)      ${{ env.CHECKSUM_HADESCRYPT }}`
          `sha256(Package.tar.gz) ${{ env.CHECKSUM_PACKAGE }}`
