name: DISABLED old Windows release

on:
  workflow_call:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use .github/workflows/release-windows.yml"
